DROP TABLE IF EXISTS user;

CREATE TABLE user
(
    id BIGINT AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,

    CONSTRAINT user_pk
    PRIMARY KEY (id)
);

